# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do

     before_all do |lane, options|
        ENV["APP_IDENTIFIER"] = "com.inventiv.multipaysdk.sample"
        ENV["APP_NAME"] = "MultiPay-SDK-Android"
     end


     lane :generate_apk do |options|

       gradle(
           task: "clean assemble",
           flavor: options[:flavor],
           build_type: options[:build_type])

     end


     lane :generate_signed_apk do |options|

        gradle(
            task: "clean assemble",
            build_type: options[:build_type],
            print_command: false,
            properties: {
                "android.injected.signing.store.file" => options[:keystore_path],
                "android.injected.signing.store.password" => options[:store_password],
                "android.injected.signing.key.alias" => options[:key_alias],
                "android.injected.signing.key.password" => options[:key_password]})
      end


     lane :run_unit_tests do
        gradle(task: "test")
     end


    lane :app_center_upload do |options|
        appcenter_upload(
            api_token: options[:app_center_api_token],
            owner_name: "inventiv",
            owner_type: "organization",
            app_name: ENV["APP_NAME"],
            file: "app/build/outputs/apk/"+options[:build_type]+"/app-"+options[:build_type]+".apk",
            destinations: "MultiPay%20SDK%20Android%20Testers",
            destination_type: "group",
            notify_testers: options[:sendNotification]
        )
    end


    lane :generate_and_upload_apk_to_app_center do |options|

        generate_signed_apk(
            build_type: options[:build_type],
            keystore_path: options[:keystore_path],
            store_password: options[:store_password],
            key_alias: options[:key_alias],
            key_password: options[:key_password]
        )

        app_center_upload(
            app_center_api_token: options[:app_center_api_token],
            build_type: options[:build_type],
            sendNotification: options[:sendNotification]
        )

    end

end