name: App Center Deployment

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type(debug, release)'
        required: true
        default: 'debug'
      send_email:
        description: 'Send email to all testers(true, false)'
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Install Fastlane Dependencies
        run: gem install bundler && bundle install

      - name: Run Unit Tests
        run: |
          fastlane run_unit_tests

      - name: Generate Signed Test Apk And Upload to App Center
        run: |
          echo "${{ secrets.TEST_KEYSTORE }}" > test.keystore.asc
          gpg -d --passphrase "${{ secrets.TEST_KEYSTORE_PASSWORD }}" --batch test.keystore.asc > test.keystore
          fastlane generate_and_upload_apk_to_app_center build_type:${{ github.event.inputs.build_type }} keystore_path:$(echo $(pwd)/test.keystore) store_password:${{ secrets.TEST_STORE_PASSWORD }} key_alias:${{ secrets.TEST_KEY_ALIAS }} key_password:${{ secrets.TEST_KEY_PASSWORD }} app_center_api_token:${{ secrets.app_center_api_token }} sendNotification:${{ github.event.inputs.send_email }} isReleaseBranch:${{ contains(github.ref, 'release/') }}
